### ISSUE TITLE
Send expression failed

### ISSUE THREAD

**Issue by chr15m** [falstro/ghost-text-vim#12]
* Ran the server.
 * Once I clicked the extension and selected the textarea I received the following error:

`Caught exception: E449: Invalid expression received: Send expression failed.`

tcl == `8.6`
tcllib == `1.18`

Can I help diagnose this further?

**Comment by falstro** [comment]
My first reaction would be that there's a incompatibility with your vim,
which version of vim are you using? Does a vim window open (but without
contents)? Stupid last question, which commit are you on if not the latest
master?

On Dec 11, 2017 3:38 AM, "Chris McCormick" <notifications@github.com> wrote:


   - Ran the server.
   - Once I clicked the extension and selected the textarea I received the
   following error:

Caught exception: E449: Invalid expression received: Send expression failed.

tcl == 8.6
tcllib == 1.18

Can I help diagnose this further?

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/falstro/ghost-text-vim/issues/12>, or mute the thread

**Comment by chr15m** [comment]
Thanks for your quick response, and for the time and effort on this software!

 * Commit is latest master: `718703ccd6579544be5ca833fa981c28dc2bf809`
 * Vim is `gvim` and version is `7.4.52`.
 * Gvim window appears and the error message shows immediately after it appears.
 * The error comes from the server, not from the clients.

Thanks!

**Comment by chr15m** [comment]
@falstro oh, I should say that I am using the Firefox version of the GhostText plugin.
